language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - chmod +x scripts/*
  - scripts/lint.sh
  # Run all tests and include coverage
  - pytest --cov=src/main/
  # Package
  - pyinstaller --onefile src/main/commit_msg_hook.py --name commit_msg.exe
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  - codecov
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
