name: "Github Action Lint"
on:
  pull_request:
    paths:
      - .github/**.yml

# For more information on actionlint, visit:
# https://github.com/rhysd/actionlint/blob/main/README.md

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash